[package]
name = "arfur"
version = "0.0.0"
edition = "2021"
license = "MIT"

[dependencies]
arfur-sys = { version = "~0.0.0", path = "../arfur-sys" }
once_cell = "~1.13.1"
thiserror = "~1.0.32"
tracing = "0.1.36"

[package.metadata.nix]
build = true
