[package]
name = "arfur-sys"
version = "0.0.0"
edition = "2021"

[build-dependencies]
tokio = { version = "1.19.2", features = ["full"] }
color-eyre = "0.6.1"
cfg-if = "1.0.0"

[features]

[package.metadata.nix]
build = true
