[package]
name = "arfur-build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindgen = "0.60.1"
color-eyre = "0.6.2"
reqwest = "0.11.11"
zip-extract = "0.1.1"
