[package]
name = "arfur-wpilib"
description = "Bindings to WPILib through autocxx."
version = "0.0.1"
edition = "2021"
license = "MIT"
rust-version = "1.62"

[dependencies]
autocxx = "0.22.4"
cxx = "1.0.75"
once_cell = "1.13.1"
thiserror = "1.0.32"
tracing = "0.1.36"

[build-dependencies]
autocxx-build = "0.22.4"
color-eyre = "0.6.2"

[build-dependencies.arfur-build]
version = "0.0.1"
path = "../arfur-build"

[build-dependencies.tokio]
version = "1.21.0"
features = ["macros", "rt-multi-thread"]

[package.metadata.nix]
build = true
