[alias]
xtask = "run --package xtask --"
x     = "xtask"

[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[target.arm-unknown-linux-gnueabi]
linker = "arm-frc2022-linux-gnueabi-gcc"
rustflags = [
  "-C", "target-cpu=cortex-a9",
]
