[package]
name = "arfur-build"
description = "Internal build tool for Arfur. Not for public use."
version = "0.0.1"

license = "MIT"
repository = "https://github.com/arfur-rs/arfur/"

edition = "2021"
rust-version = "1.62"

[dependencies]
color-eyre = "0.6.2"
reqwest = "0.11.11"
zip-extract = "0.1.1"
